apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- development-patches.yaml

configMapGenerator:
- name: jbx-config
  behavior: merge
  literals:
  - NODE_ENV=development
  - LOG_LEVEL=debug
