apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: jbx
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: LOG_LEVEL
          value: "info"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: jbx
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-worker
  namespace: jbx
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: automation-worker
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
