apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: jbx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jbx/backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: jbx-config
              key: NODE_ENV
        - name: MONGODB_URL
          value: "mongodb://jbx:$(MONGODB_PASSWORD)@mongodb-service:27017/jbx"
        - name: POSTGRES_URL
          value: "postgresql://jbx:$(POSTGRES_PASSWORD)@postgres-service:5432/jbx"
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: jbx-config
              key: REDIS_URL
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: jbx-config
              key: RABBITMQ_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jbx-secrets
              key: JWT_SECRET
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jbx-secrets
              key: POSTGRES_PASSWORD
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jbx-secrets
              key: MONGODB_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: jbx
spec:
  selector:
    app: backend
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP
