apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: jbx
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            memory: "384Mi"
            cpu: "300m"
          limits:
            memory: "768Mi"
            cpu: "600m"
        env:
        - name: LOG_LEVEL
          value: "debug"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: jbx
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-worker
  namespace: jbx
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: automation-worker
        resources:
          requests:
            memory: "384Mi"
            cpu: "300m"
          limits:
            memory: "768Mi"
            cpu: "600m"
